/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package supermarket;

import com.sun.org.apache.xml.internal.security.utils.HelperNodeList;

/**
 *
 * @author synapse
 */
public class UserLevel extends javax.swing.JFrame {

    /**
     * Creates new form UserLevel
     */
    public UserLevel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adminGroup = new javax.swing.ButtonGroup();
        goodsGroup = new javax.swing.ButtonGroup();
        customerGroup = new javax.swing.ButtonGroup();
        salesGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        admin_add = new javax.swing.JRadioButton();
        admin_read = new javax.swing.JRadioButton();
        admin_none = new javax.swing.JRadioButton();
        admin_delete = new javax.swing.JRadioButton();
        admin_edit = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        customer_edit = new javax.swing.JRadioButton();
        customer_delete = new javax.swing.JRadioButton();
        customer_none = new javax.swing.JRadioButton();
        customer_add = new javax.swing.JRadioButton();
        customer_read = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        goods_edit = new javax.swing.JRadioButton();
        goods_read = new javax.swing.JRadioButton();
        goods_none = new javax.swing.JRadioButton();
        goods_add = new javax.swing.JRadioButton();
        goods_delete = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        sales_edit = new javax.swing.JRadioButton();
        sales_none = new javax.swing.JRadioButton();
        sales_read = new javax.swing.JRadioButton();
        sales_delete = new javax.swing.JRadioButton();
        sales_add = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("User Permissions");

        adminGroup.add(admin_add);
        admin_add.setText("Add");

        adminGroup.add(admin_read);
        admin_read.setText("Read");

        adminGroup.add(admin_none);
        admin_none.setText("None");

        adminGroup.add(admin_delete);
        admin_delete.setText("Delete");

        adminGroup.add(admin_edit);
        admin_edit.setText("Edit");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(admin_read)
                    .addComponent(admin_add)
                    .addComponent(admin_edit)
                    .addComponent(admin_delete)
                    .addComponent(admin_none))
                .addContainerGap(342, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {admin_add, admin_delete, admin_edit, admin_none, admin_read});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(admin_none, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(admin_read, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(admin_add)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(admin_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(admin_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {admin_add, admin_delete, admin_edit, admin_none, admin_read});

        jTabbedPane1.addTab("Admin Level", jPanel1);

        customerGroup.add(customer_edit);
        customer_edit.setText("Edit");

        customerGroup.add(customer_delete);
        customer_delete.setText("Delete");

        customerGroup.add(customer_none);
        customer_none.setText("None");

        customerGroup.add(customer_add);
        customer_add.setText("Add");

        customerGroup.add(customer_read);
        customer_read.setText("Read");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(customer_read)
                    .addComponent(customer_none)
                    .addComponent(customer_add)
                    .addComponent(customer_edit)
                    .addComponent(customer_delete))
                .addContainerGap(353, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(customer_none, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(customer_read, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(customer_add, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addGap(3, 3, 3)
                .addComponent(customer_edit, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(customer_delete, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Customer Level", jPanel2);

        goodsGroup.add(goods_edit);
        goods_edit.setText("Edit");

        goodsGroup.add(goods_read);
        goods_read.setText("Read");

        goodsGroup.add(goods_none);
        goods_none.setText("None");

        goodsGroup.add(goods_add);
        goods_add.setText("Add");

        goodsGroup.add(goods_delete);
        goods_delete.setText("Delete");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(goods_read)
                    .addComponent(goods_none)
                    .addComponent(goods_add)
                    .addComponent(goods_edit)
                    .addComponent(goods_delete))
                .addContainerGap(354, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(goods_none, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(goods_read, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(goods_add, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(goods_edit, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(goods_delete, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                .addGap(9, 9, 9))
        );

        jTabbedPane1.addTab("Goods Level", jPanel3);

        salesGroup.add(sales_edit);
        sales_edit.setText("Level 3: Edit");

        salesGroup.add(sales_none);
        sales_none.setText("Level 0: None");

        salesGroup.add(sales_read);
        sales_read.setText("Level 1: Read");

        salesGroup.add(sales_delete);
        sales_delete.setText("Level 4: Delete");

        salesGroup.add(sales_add);
        sales_add.setText("Level 2: Add");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sales_delete)
                    .addComponent(sales_edit)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(sales_none)
                        .addComponent(sales_add, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(sales_read, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(317, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sales_none, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sales_read, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sales_add, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sales_edit, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sales_delete, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addGap(13, 13, 13))
        );

        jTabbedPane1.addTab("Sales Level", jPanel4);

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jLabel1)
                .addContainerGap(236, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1))
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:


        Helper.Tools.setCenter(this);

        DAL d = new DAL();

        d.rs = d.executeQuery("SELECT username FROM users WHERE user_id=" + UserList.user_id);

        try {
            d.rs.next();

            jLabel1.setText(d.rs.getString("username") + "'s Permissions");

        } catch (Exception e) {
        }


        d.rs = d.executeQuery("SELECT * FROM user_level WHERE user_id=" + UserList.user_id);

        try {
            d.rs.next();
            
            int admin_level = d.rs.getInt("admin_level");
            int customer_level = d.rs.getInt("customer_level");
            int goods_level = d.rs.getInt("goods_level");
            int sales_level = d.rs.getInt("sales_level");
            
            if(admin_level == 0) {
                admin_none.setSelected(true);
            }
            else if(admin_level == 1) {
                admin_read.setSelected(true);
            }
            else if(admin_level == 2) {
                admin_add.setSelected(true);
            }
            else if(admin_level == 4) {
                admin_edit.setSelected(true);
            }
            else if(admin_level == 8) {
                admin_delete.setSelected(true);
            }
            
            
            if(goods_level == 0) {
                goods_none.setSelected(true);
            }
            else if(goods_level == 1) {
                goods_read.setSelected(true);
            }
            else if(goods_level == 2) {
                goods_add.setSelected(true);
            }
            else if(goods_level == 4) {
                goods_edit.setSelected(true);
            }
            else if(goods_level == 8) {
                goods_delete.setSelected(true);
            }
            
            
            if(customer_level == 0) {
                customer_none.setSelected(true);
            }
            else if(customer_level == 1) {
                customer_read.setSelected(true);
            }
            else if(customer_level == 2) {
                customer_add.setSelected(true);
            }
            else if(customer_level == 4) {
                customer_edit.setSelected(true);
            }
            else if(customer_level == 8) {
                customer_delete.setSelected(true);
            }
            
            
            if(sales_level == 0) {
                sales_none.setSelected(true);
            }
            else if(sales_level == 1) {
                sales_read.setSelected(true);
            }
            else if(sales_level == 2) {
                sales_add.setSelected(true);
            }
            else if(sales_level == 4) {
                sales_edit.setSelected(true);
            }
            else if(sales_level == 8) {
                sales_delete.setSelected(true);
            }
            
            
        } catch (Exception e) {
        }





    }//GEN-LAST:event_formWindowOpened

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        int admin_level = 0;
        int customer_level = 0;
        int goods_level = 0;
        int sales_level = 0;
        
        if(admin_read.isSelected()) {
            admin_level = 1;
        }
        else if(admin_add.isSelected()) {
            admin_level = 2;
        }
        else if(admin_edit.isSelected()) {
            admin_level = 4;
        }
        else if(admin_delete.isSelected()) {
            admin_level = 8;
        }
        
        if(customer_read.isSelected()) {
            customer_level = 1;
        }
        else if(customer_add.isSelected()) {
            customer_level = 2;
        }
        else if(customer_edit.isSelected()) {
            customer_level = 4;
        }
        else if(customer_delete.isSelected()) {
            customer_level = 8;
        }
        
        if(goods_read.isSelected()) {
            goods_level = 1;
        }
        else if(goods_add.isSelected()) {
            goods_level = 2;
        }
        else if(goods_edit.isSelected()) {
            goods_level = 4;
        }
        else if(goods_delete.isSelected()) {
            goods_level = 8;
        }
        
        if(sales_read.isSelected()) {
            sales_level = 1;
        }
        else if(sales_add.isSelected()) {
            sales_level = 2;
        }
        else if(sales_edit.isSelected()) {
            sales_level = 4;
        }
        else if(sales_delete.isSelected()) {
            sales_level = 8;
        }
        
        
        DAL d = new DAL();
        
        String command = "UPDATE user_level SET admin_level=%d, goods_level=%d, customer_level=%d, sales_level=%d WHERE user_id=%d";
 
        command = String.format(command, admin_level, goods_level, customer_level, sales_level, UserList.user_id);
        
        if(d.execute(command)) {
            Helper.Tools.show("Permission Successfully Updated!");
            this.setVisible(false);
        }
        else {
            Helper.Tools.show("Error! Please Try Again!");
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;


                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserLevel.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserLevel.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserLevel.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserLevel.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserLevel().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup adminGroup;
    private javax.swing.JRadioButton admin_add;
    private javax.swing.JRadioButton admin_delete;
    private javax.swing.JRadioButton admin_edit;
    private javax.swing.JRadioButton admin_none;
    private javax.swing.JRadioButton admin_read;
    private javax.swing.ButtonGroup customerGroup;
    private javax.swing.JRadioButton customer_add;
    private javax.swing.JRadioButton customer_delete;
    private javax.swing.JRadioButton customer_edit;
    private javax.swing.JRadioButton customer_none;
    private javax.swing.JRadioButton customer_read;
    private javax.swing.ButtonGroup goodsGroup;
    private javax.swing.JRadioButton goods_add;
    private javax.swing.JRadioButton goods_delete;
    private javax.swing.JRadioButton goods_edit;
    private javax.swing.JRadioButton goods_none;
    private javax.swing.JRadioButton goods_read;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.ButtonGroup salesGroup;
    private javax.swing.JRadioButton sales_add;
    private javax.swing.JRadioButton sales_delete;
    private javax.swing.JRadioButton sales_edit;
    private javax.swing.JRadioButton sales_none;
    private javax.swing.JRadioButton sales_read;
    // End of variables declaration//GEN-END:variables
}
